export const cardRegistry = {
  magician: require("./magician.jpg"),
  priestess: require("./priestess.jpg"),
  empress: require("./empress.jpg"),
  emperor: require("./emperor.jpg"),
  hierophant: require("./hierophant.jpg"),
  lovers: require("./lovers.jpg"),
  chariot: require("./chariot.jpg"),
  justice: require("./justice.jpg"),
  hermit: require("./hermit.jpg"),
  fortune: require("./fortune.jpg"),
  strenght: require("./strenght.jpg"),
  hanged: require("./hanged.jpg"),
  death: require("./death.jpg"),
  temperance: require("./temperance.jpg"),
  devil: require("./devil.jpg"),
  tower: require("./tower.jpg"),
  star: require("./star.jpg"),
  moon: require("./moon.jpg"),
  sun: require("./sun.jpg"),
  judgement: require("./judgement.jpg"),
  world: require("./world.jpg"),
  fool: require("./fool.jpg"),
  revers: require("./revers.jpg"),
} as const;
